version: "3.7"

services:

  rng:
    build:
      context: ./rng
      args: # from env_file
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    env_file:
      - .env
    ports:
      - "8001:80"

  hasher:
    build: hasher
    ports:
      - "8002:80"

  webui:
    build: webui
    ports:
      - "8000:80"
    volumes:
      - "./webui/static/:/static/"

  redis:
    image: redis

  worker:
    build: worker
